services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - website-network

  adminer:
    image: adminer
    container_name: adminer
    env_file:
      - ./.env
    ports:
      - '2121:8080'
    networks:
      - website-network

  minio:
    image: minio/minio
    container_name: minio
    env_file:
      - .env
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - website-network

  smtp:
    image: ghcr.io/devture/exim-relay:latest
    container_name: smtp
    env_file:
      - .env
    ports:
      - '8026:8025'

networks:
  website-network:
