import type { Metadata } from "next";
import "@/styles/global.css";

export const metadata: Metadata = {
  title: "Amir Tanazzoh Website",
  description: "Generated by create next app",
};

export default function RootLayout ( { children, }: Readonly<{ children: React.ReactNode; }> )
{
  return (
    <html lang="en" suppressHydrationWarning>
      <body >
        { children }
      </body>
    </html>
  );
}
